#!/bin/bash
#
# Session Save Script
# Creates a human-readable summary of the current/last session
# Auto-generates description from first user message if not provided
#
# Usage: session-save [description]
#

SUMMARIES_DIR="$HOME/.claude/session-summaries"
TRANSCRIPTS_DIR="$HOME/.claude/projects"

mkdir -p "$SUMMARIES_DIR"

# Find most recent transcript
LATEST=$(ls -t "$TRANSCRIPTS_DIR"/*/*.jsonl 2>/dev/null | head -1)

if [[ -z "$LATEST" ]]; then
    echo "No session transcripts found"
    exit 1
fi

# Auto-generate description if not provided
if [[ -n "$1" ]]; then
    DESC="$1"
else
    # Extract first user message and create slug
    FIRST_MSG=$(grep -m1 '"type":"user"' "$LATEST" 2>/dev/null | \
        python3 -c "import sys,json; d=json.loads(sys.stdin.read()); print(d.get('message',{}).get('content','session')[:50])" 2>/dev/null || echo "session")
    # Clean up: take first 5 words, remove special chars
    DESC=$(echo "$FIRST_MSG" | tr -cd '[:alnum:] ' | awk '{for(i=1;i<=5&&i<=NF;i++) printf $i"-"; print ""}' | sed 's/-$//')
    [[ -z "$DESC" ]] && DESC="session"
fi

SESSION_ID=$(basename "$LATEST" .jsonl)
DATE=$(date '+%Y-%m-%d')
TIME=$(date '+%H%M')

# Get session stats
MESSAGES=$(grep -c '"type":"user"\|"type":"assistant"' "$LATEST" 2>/dev/null || echo "0")
TOOLS=$(grep -c '"type":"tool_use"' "$LATEST" 2>/dev/null || echo "0")
SIZE=$(ls -lh "$LATEST" | awk '{print $5}')

# Extract context: files edited, tools used, working directory
FILES_EDITED=$(grep -o '"file_path":"[^"]*"' "$LATEST" 2>/dev/null | sed 's/"file_path":"//g; s/"//g' | sort -u | head -10 | tr '\n' '\n- ' | sed 's/^/- /')
TOOLS_USED=$(grep -o '"name":"[^"]*"' "$LATEST" 2>/dev/null | sed 's/"name":"//g; s/"//g' | grep -E '^(Bash|Read|Edit|Write|Grep|Glob|Task|WebFetch)$' | sort | uniq -c | sort -rn | head -5 | awk '{print $2"("$1")"}' | tr '\n' ' ')
PWD_USED=$(grep -o '"cwd":"[^"]*"' "$LATEST" 2>/dev/null | head -1 | sed 's/"cwd":"//g; s/"//g')

# Extract key topics from user messages (first 3 unique topics)
TOPICS=$(grep '"type":"user"' "$LATEST" 2>/dev/null | \
    python3 -c "
import sys, json, re
from collections import Counter
words = Counter()
for line in sys.stdin:
    try:
        d = json.loads(line)
        content = d.get('message',{}).get('content','')
        # Extract keywords (nouns, verbs)
        for w in re.findall(r'\b[a-z]{4,15}\b', content.lower()):
            if w not in ['that','this','with','from','have','what','your','would','could','should','about','just','like','into','make','when','been','there','which','their','will','more','some','them','then','than']:
                words[w] += 1
    except: pass
print(', '.join([w for w,c in words.most_common(8)]))
" 2>/dev/null || echo "general")

# Create summary filename
SLUG=$(echo "$DESC" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -cd '[:alnum:]-')
SUMMARY_FILE="$SUMMARIES_DIR/${DATE}_${TIME}_${SLUG}.md"

# Write summary
cat > "$SUMMARY_FILE" << EOF
# Session: $DESC

**Date:** $DATE $(date '+%H:%M')
**Session ID:** $SESSION_ID
**Transcript:** $LATEST
**Size:** $SIZE
**Working Dir:** ${PWD_USED:-unknown}

## Stats
- Messages: ~$MESSAGES
- Tool calls: ~$TOOLS
- Top tools: ${TOOLS_USED:-none}

## Context
**Key Topics:** ${TOPICS:-general}

**Files Touched:**
${FILES_EDITED:-none}

## Notes
_Add your notes here_

---
*Auto-generated by session-save*
EOF

echo "✅ Session saved to: $SUMMARY_FILE"
echo ""
echo "Transcript: $LATEST ($SIZE)"
echo "Messages: ~$MESSAGES | Tools: ~$TOOLS"
